# Sheldon configuration file

shell = "zsh"

[plugins]

# Completions
[plugins.zsh-rustup-completion]
github = "pkulev/zsh-rustup-completion"

[plugins.zsh-cargo-completion]
github = "MenkeTechnologies/zsh-cargo-completion"
