#!/bin/bash

function bootup() {
    local command=$1
    which $command > /dev/null && pgrep $command || $command &
}

XSESSION="i3wm"

eval $(gnome-keyring-daemon --components=pkcs11,scretes,ssh,gpg)

export GNOME_KEYRING_PID
export GNOME_KEYRING_SCOKET
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

if [ -e /usr/bin/ibus ]; then
    IM_PROGRAM=ibus
fi

if [ -e /usr/bin/fcitx ]; then
    IM_PROGRAM=fcitx
fi

export XMODIFIERS=@im="${IM_PROGRAM}"
export GTK_IM_MODULE="${IM_PROGRAM}"
export QT_IM_MODULE="${IM_PROGRAM}"
