[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available / $total "

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization $frequency{ $boost|} "
format_alt = " $icon $barchart $utilization $frequency{ $boost|} "

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) 5m: $5m.eng(w:4) 15m: $5m.eng(w:4) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:3) $icon_swap $swap_used_percents.eng(w:3) "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%Y/%m/%d %a %T') "
