#!/usr/sbin/nft -f

destroy table inet local_ssh

define public_if = "eth0"
define ssh_allowed_if = { "lo", "tailscale0", "wg0" }
define ssh_port = 2222

table inet local_ssh {
  chain input {
    type filter hook input priority -10; policy accept;
    iifname != $ssh_allowed_if tcp dport $ssh_port drop
  }
}
